
/*  AUTOMATICALLY CONVERTED FILE  */

package enums;

public enum eGMCommands {
	GMMessage, showName, OnlineRoyalArmy, OnlineChaosLegion, GoNearby, comment, serverTime, Where, CreaturesInMap, WarpMeToTarget, WarpChar, Silence, SOSShowList, SOSRemove, GoToChar, invisible, GMPanel, RequestUserList, Working, Hiding, Jail, KillNPC, WarnUser, EditChar, RequestCharInfo, RequestCharStats, RequestCharGold, RequestCharInventory, RequestCharBank, RequestCharSkills, ReviveChar, OnlineGM, OnlineMap, Forgive, Kick, Execute, BanChar, UnbanChar, NPCFollow, SummonChar, SpawnListRequest, SpawnCreature, ResetNPCInventory, CleanWorld, ServerMessage, NickToIP, IPToNick, GuildOnlineMembers, TeleportCreate, TeleportDestroy, RainToggle, SetCharDescription, ForceMIDIToMap, ForceWAVEToMap, RoyalArmyMessage, ChaosLegionMessage, CitizenMessage, CriminalMessage, TalkAsNPC, DestroyAllItemsInArea, AcceptRoyalCouncilMember, AcceptChaosCouncilMember, ItemsInTheFloor, MakeDumb, MakeDumbNoMore, DumpIPTables, CouncilKick, SetTrigger, AskTrigger, BannedIPList, BannedIPReload, GuildMemberList, GuildBan, BanIP, UnbanIP, CreateItem, DestroyItems, ChaosLegionKick, RoyalArmyKick, ForceMIDIAll, ForceWAVEAll, RemovePunishment, TileBlockedToggle, KillNPCNoRespawn, KillAllNearbyNPCs, LastIP, ChangeMOTD, SetMOTD, SystemMessage, CreateNPC, CreateNPCWithRespawn, ImperialArmour, ChaosArmour, NavigateToggle, ServerOpenToUsersToggle, TurnOffServer, TurnCriminal, ResetFactions, RemoveCharFromGuild, RequestCharMail, AlterPassword, AlterMail, AlterName, ToggleCentinelActivated, DoBackUp, ShowGuildMessages, SaveMap, ChangeMapInfoPK, ChangeMapInfoBackup, ChangeMapInfoRestricted, ChangeMapInfoNoMagic, ChangeMapInfoNoInvi, ChangeMapInfoNoResu, ChangeMapInfoLand, ChangeMapInfoZone, ChangeMapInfoStealNpc, ChangeMapInfoNoOcultar, ChangeMapInfoNoInvocar, SaveChars, CleanSOS, ShowServerForm, night, KickAllChars, ReloadNPCs, ReloadServerIni, ReloadSpells, ReloadObjects, Restart, ResetAutoUpdate, ChatColor, Ignored, CheckSlot, SetIniVar, CreatePretorianClan, RemovePretorianClan, EnableDenounces, ShowDenouncesList, MapMessage, SetDialog, Impersonate, Imitate, RecordAdd, RecordRemove, RecordAddObs, RecordListRequest, RecordDetailsRequest, AlterGuildName, HigherAdminsMessage;
	public static eGMCommands fromInteger(int x) {
		switch (x) {
		case 1:
			return GMMessage;
		case 2:
			return showName;
		case 3:
			return OnlineRoyalArmy;
		case 4:
			return OnlineChaosLegion;
		case 5:
			return GoNearby;
		case 6:
			return comment;
		case 7:
			return serverTime;
		case 8:
			return Where;
		case 9:
			return CreaturesInMap;
		case 10:
			return WarpMeToTarget;
		case 11:
			return WarpChar;
		case 12:
			return Silence;
		case 13:
			return SOSShowList;
		case 14:
			return SOSRemove;
		case 15:
			return GoToChar;
		case 16:
			return invisible;
		case 17:
			return GMPanel;
		case 18:
			return RequestUserList;
		case 19:
			return Working;
		case 20:
			return Hiding;
		case 21:
			return Jail;
		case 22:
			return KillNPC;
		case 23:
			return WarnUser;
		case 24:
			return EditChar;
		case 25:
			return RequestCharInfo;
		case 26:
			return RequestCharStats;
		case 27:
			return RequestCharGold;
		case 28:
			return RequestCharInventory;
		case 29:
			return RequestCharBank;
		case 30:
			return RequestCharSkills;
		case 31:
			return ReviveChar;
		case 32:
			return OnlineGM;
		case 33:
			return OnlineMap;
		case 34:
			return Forgive;
		case 35:
			return Kick;
		case 36:
			return Execute;
		case 37:
			return BanChar;
		case 38:
			return UnbanChar;
		case 39:
			return NPCFollow;
		case 40:
			return SummonChar;
		case 41:
			return SpawnListRequest;
		case 42:
			return SpawnCreature;
		case 43:
			return ResetNPCInventory;
		case 44:
			return CleanWorld;
		case 45:
			return ServerMessage;
		case 46:
			return NickToIP;
		case 47:
			return IPToNick;
		case 48:
			return GuildOnlineMembers;
		case 49:
			return TeleportCreate;
		case 50:
			return TeleportDestroy;
		case 51:
			return RainToggle;
		case 52:
			return SetCharDescription;
		case 53:
			return ForceMIDIToMap;
		case 54:
			return ForceWAVEToMap;
		case 55:
			return RoyalArmyMessage;
		case 56:
			return ChaosLegionMessage;
		case 57:
			return CitizenMessage;
		case 58:
			return CriminalMessage;
		case 59:
			return TalkAsNPC;
		case 60:
			return DestroyAllItemsInArea;
		case 61:
			return AcceptRoyalCouncilMember;
		case 62:
			return AcceptChaosCouncilMember;
		case 63:
			return ItemsInTheFloor;
		case 64:
			return MakeDumb;
		case 65:
			return MakeDumbNoMore;
		case 66:
			return DumpIPTables;
		case 67:
			return CouncilKick;
		case 68:
			return SetTrigger;
		case 69:
			return AskTrigger;
		case 70:
			return BannedIPList;
		case 71:
			return BannedIPReload;
		case 72:
			return GuildMemberList;
		case 73:
			return GuildBan;
		case 74:
			return BanIP;
		case 75:
			return UnbanIP;
		case 76:
			return CreateItem;
		case 77:
			return DestroyItems;
		case 78:
			return ChaosLegionKick;
		case 79:
			return RoyalArmyKick;
		case 80:
			return ForceMIDIAll;
		case 81:
			return ForceWAVEAll;
		case 82:
			return RemovePunishment;
		case 83:
			return TileBlockedToggle;
		case 84:
			return KillNPCNoRespawn;
		case 85:
			return KillAllNearbyNPCs;
		case 86:
			return LastIP;
		case 87:
			return ChangeMOTD;
		case 88:
			return SetMOTD;
		case 89:
			return SystemMessage;
		case 90:
			return CreateNPC;
		case 91:
			return CreateNPCWithRespawn;
		case 92:
			return ImperialArmour;
		case 93:
			return ChaosArmour;
		case 94:
			return NavigateToggle;
		case 95:
			return ServerOpenToUsersToggle;
		case 96:
			return TurnOffServer;
		case 97:
			return TurnCriminal;
		case 98:
			return ResetFactions;
		case 99:
			return RemoveCharFromGuild;
		case 100:
			return RequestCharMail;
		case 101:
			return AlterPassword;
		case 102:
			return AlterMail;
		case 103:
			return AlterName;
		case 104:
			return ToggleCentinelActivated;
		case 105:
			return DoBackUp;
		case 106:
			return ShowGuildMessages;
		case 107:
			return SaveMap;
		case 108:
			return ChangeMapInfoPK;
		case 109:
			return ChangeMapInfoBackup;
		case 110:
			return ChangeMapInfoRestricted;
		case 111:
			return ChangeMapInfoNoMagic;
		case 112:
			return ChangeMapInfoNoInvi;
		case 113:
			return ChangeMapInfoNoResu;
		case 114:
			return ChangeMapInfoLand;
		case 115:
			return ChangeMapInfoZone;
		case 116:
			return ChangeMapInfoStealNpc;
		case 117:
			return ChangeMapInfoNoOcultar;
		case 118:
			return ChangeMapInfoNoInvocar;
		case 119:
			return SaveChars;
		case 120:
			return CleanSOS;
		case 121:
			return ShowServerForm;
		case 122:
			return night;
		case 123:
			return KickAllChars;
		case 124:
			return ReloadNPCs;
		case 125:
			return ReloadServerIni;
		case 126:
			return ReloadSpells;
		case 127:
			return ReloadObjects;
		case 128:
			return Restart;
		case 129:
			return ResetAutoUpdate;
		case 130:
			return ChatColor;
		case 131:
			return Ignored;
		case 132:
			return CheckSlot;
		case 133:
			return SetIniVar;
		case 134:
			return CreatePretorianClan;
		case 135:
			return RemovePretorianClan;
		case 136:
			return EnableDenounces;
		case 137:
			return ShowDenouncesList;
		case 138:
			return MapMessage;
		case 139:
			return SetDialog;
		case 140:
			return Impersonate;
		case 141:
			return Imitate;
		case 142:
			return RecordAdd;
		case 143:
			return RecordRemove;
		case 144:
			return RecordAddObs;
		case 145:
			return RecordListRequest;
		case 146:
			return RecordDetailsRequest;
		case 147:
			return AlterGuildName;
		case 148:
			return HigherAdminsMessage;
		}
		return null;
	}

	public static int toInteger(eGMCommands x) {
		switch (x) {
		case GMMessage:
			return 1;
		case showName:
			return 2;
		case OnlineRoyalArmy:
			return 3;
		case OnlineChaosLegion:
			return 4;
		case GoNearby:
			return 5;
		case comment:
			return 6;
		case serverTime:
			return 7;
		case Where:
			return 8;
		case CreaturesInMap:
			return 9;
		case WarpMeToTarget:
			return 10;
		case WarpChar:
			return 11;
		case Silence:
			return 12;
		case SOSShowList:
			return 13;
		case SOSRemove:
			return 14;
		case GoToChar:
			return 15;
		case invisible:
			return 16;
		case GMPanel:
			return 17;
		case RequestUserList:
			return 18;
		case Working:
			return 19;
		case Hiding:
			return 20;
		case Jail:
			return 21;
		case KillNPC:
			return 22;
		case WarnUser:
			return 23;
		case EditChar:
			return 24;
		case RequestCharInfo:
			return 25;
		case RequestCharStats:
			return 26;
		case RequestCharGold:
			return 27;
		case RequestCharInventory:
			return 28;
		case RequestCharBank:
			return 29;
		case RequestCharSkills:
			return 30;
		case ReviveChar:
			return 31;
		case OnlineGM:
			return 32;
		case OnlineMap:
			return 33;
		case Forgive:
			return 34;
		case Kick:
			return 35;
		case Execute:
			return 36;
		case BanChar:
			return 37;
		case UnbanChar:
			return 38;
		case NPCFollow:
			return 39;
		case SummonChar:
			return 40;
		case SpawnListRequest:
			return 41;
		case SpawnCreature:
			return 42;
		case ResetNPCInventory:
			return 43;
		case CleanWorld:
			return 44;
		case ServerMessage:
			return 45;
		case NickToIP:
			return 46;
		case IPToNick:
			return 47;
		case GuildOnlineMembers:
			return 48;
		case TeleportCreate:
			return 49;
		case TeleportDestroy:
			return 50;
		case RainToggle:
			return 51;
		case SetCharDescription:
			return 52;
		case ForceMIDIToMap:
			return 53;
		case ForceWAVEToMap:
			return 54;
		case RoyalArmyMessage:
			return 55;
		case ChaosLegionMessage:
			return 56;
		case CitizenMessage:
			return 57;
		case CriminalMessage:
			return 58;
		case TalkAsNPC:
			return 59;
		case DestroyAllItemsInArea:
			return 60;
		case AcceptRoyalCouncilMember:
			return 61;
		case AcceptChaosCouncilMember:
			return 62;
		case ItemsInTheFloor:
			return 63;
		case MakeDumb:
			return 64;
		case MakeDumbNoMore:
			return 65;
		case DumpIPTables:
			return 66;
		case CouncilKick:
			return 67;
		case SetTrigger:
			return 68;
		case AskTrigger:
			return 69;
		case BannedIPList:
			return 70;
		case BannedIPReload:
			return 71;
		case GuildMemberList:
			return 72;
		case GuildBan:
			return 73;
		case BanIP:
			return 74;
		case UnbanIP:
			return 75;
		case CreateItem:
			return 76;
		case DestroyItems:
			return 77;
		case ChaosLegionKick:
			return 78;
		case RoyalArmyKick:
			return 79;
		case ForceMIDIAll:
			return 80;
		case ForceWAVEAll:
			return 81;
		case RemovePunishment:
			return 82;
		case TileBlockedToggle:
			return 83;
		case KillNPCNoRespawn:
			return 84;
		case KillAllNearbyNPCs:
			return 85;
		case LastIP:
			return 86;
		case ChangeMOTD:
			return 87;
		case SetMOTD:
			return 88;
		case SystemMessage:
			return 89;
		case CreateNPC:
			return 90;
		case CreateNPCWithRespawn:
			return 91;
		case ImperialArmour:
			return 92;
		case ChaosArmour:
			return 93;
		case NavigateToggle:
			return 94;
		case ServerOpenToUsersToggle:
			return 95;
		case TurnOffServer:
			return 96;
		case TurnCriminal:
			return 97;
		case ResetFactions:
			return 98;
		case RemoveCharFromGuild:
			return 99;
		case RequestCharMail:
			return 100;
		case AlterPassword:
			return 101;
		case AlterMail:
			return 102;
		case AlterName:
			return 103;
		case ToggleCentinelActivated:
			return 104;
		case DoBackUp:
			return 105;
		case ShowGuildMessages:
			return 106;
		case SaveMap:
			return 107;
		case ChangeMapInfoPK:
			return 108;
		case ChangeMapInfoBackup:
			return 109;
		case ChangeMapInfoRestricted:
			return 110;
		case ChangeMapInfoNoMagic:
			return 111;
		case ChangeMapInfoNoInvi:
			return 112;
		case ChangeMapInfoNoResu:
			return 113;
		case ChangeMapInfoLand:
			return 114;
		case ChangeMapInfoZone:
			return 115;
		case ChangeMapInfoStealNpc:
			return 116;
		case ChangeMapInfoNoOcultar:
			return 117;
		case ChangeMapInfoNoInvocar:
			return 118;
		case SaveChars:
			return 119;
		case CleanSOS:
			return 120;
		case ShowServerForm:
			return 121;
		case night:
			return 122;
		case KickAllChars:
			return 123;
		case ReloadNPCs:
			return 124;
		case ReloadServerIni:
			return 125;
		case ReloadSpells:
			return 126;
		case ReloadObjects:
			return 127;
		case Restart:
			return 128;
		case ResetAutoUpdate:
			return 129;
		case ChatColor:
			return 130;
		case Ignored:
			return 131;
		case CheckSlot:
			return 132;
		case SetIniVar:
			return 133;
		case CreatePretorianClan:
			return 134;
		case RemovePretorianClan:
			return 135;
		case EnableDenounces:
			return 136;
		case ShowDenouncesList:
			return 137;
		case MapMessage:
			return 138;
		case SetDialog:
			return 139;
		case Impersonate:
			return 140;
		case Imitate:
			return 141;
		case RecordAdd:
			return 142;
		case RecordRemove:
			return 143;
		case RecordAddObs:
			return 144;
		case RecordListRequest:
			return 145;
		case RecordDetailsRequest:
			return 146;
		case AlterGuildName:
			return 147;
		case HigherAdminsMessage:
			return 148;
		}
		return 0;
	}
}
