
/*  AUTOMATICALLY CONVERTED FILE  */

package enums;

public enum ServerPacketID {
	Logged, RemoveDialogs, RemoveCharDialog, NavigateToggle, Disconnect, CommerceEnd, BankEnd, CommerceInit, BankInit, UserCommerceInit, UserCommerceEnd, UserOfferConfirm, CommerceChat, ShowBlacksmithForm, ShowCarpenterForm, UpdateSta, UpdateMana, UpdateHP, UpdateGold, UpdateBankGold, UpdateExp, ChangeMap, PosUpdate, ChatOverHead, ConsoleMsg, GuildChat, ShowMessageBox, UserIndexInServer, UserCharIndexInServer, CharacterCreate, CharacterRemove, CharacterChangeNick, CharacterMove, ForceCharMove, CharacterChange, ObjectCreate, ObjectDelete, BlockPosition, PlayMidi, PlayWave, guildList, AreaChanged, PauseToggle, RainToggle, CreateFX, UpdateUserStats, WorkRequestTarget, ChangeInventorySlot, ChangeBankSlot, ChangeSpellSlot, Atributes, BlacksmithWeapons, BlacksmithArmors, CarpenterObjects, RestOK, ErrorMsg, Blind, Dumb, ShowSignal, ChangeNPCInventorySlot, UpdateHungerAndThirst, Fame, MiniStats, LevelUp, AddForumMsg, ShowForumForm, SetInvisible, DiceRoll, MeditateToggle, BlindNoMore, DumbNoMore, SendSkills, TrainerCreatureList, guildNews, OfferDetails, AlianceProposalsList, PeaceProposalsList, CharacterInfo, GuildLeaderInfo, GuildMemberInfo, GuildDetails, ShowGuildFundationForm, ParalizeOK, ShowUserRequest, TradeOK, BankOK, ChangeUserTradeSlot, SendNight, Pong, UpdateTagAndStatus, SpawnList, ShowSOSForm, ShowMOTDEditionForm, ShowGMPanelForm, UserNameList, ShowDenounces, RecordList, RecordDetails, ShowGuildAlign, ShowPartyForm, UpdateStrenghtAndDexterity, UpdateStrenght, UpdateDexterity, AddSlots, MultiMessage, StopWorking, CancelOfferItem;
	public static ServerPacketID fromInteger(int x) {
		switch (x) {
		case 0:
			return Logged;
		case 1:
			return RemoveDialogs;
		case 2:
			return RemoveCharDialog;
		case 3:
			return NavigateToggle;
		case 4:
			return Disconnect;
		case 5:
			return CommerceEnd;
		case 6:
			return BankEnd;
		case 7:
			return CommerceInit;
		case 8:
			return BankInit;
		case 9:
			return UserCommerceInit;
		case 10:
			return UserCommerceEnd;
		case 11:
			return UserOfferConfirm;
		case 12:
			return CommerceChat;
		case 13:
			return ShowBlacksmithForm;
		case 14:
			return ShowCarpenterForm;
		case 15:
			return UpdateSta;
		case 16:
			return UpdateMana;
		case 17:
			return UpdateHP;
		case 18:
			return UpdateGold;
		case 19:
			return UpdateBankGold;
		case 20:
			return UpdateExp;
		case 21:
			return ChangeMap;
		case 22:
			return PosUpdate;
		case 23:
			return ChatOverHead;
		case 24:
			return ConsoleMsg;
		case 25:
			return GuildChat;
		case 26:
			return ShowMessageBox;
		case 27:
			return UserIndexInServer;
		case 28:
			return UserCharIndexInServer;
		case 29:
			return CharacterCreate;
		case 30:
			return CharacterRemove;
		case 31:
			return CharacterChangeNick;
		case 32:
			return CharacterMove;
		case 33:
			return ForceCharMove;
		case 34:
			return CharacterChange;
		case 35:
			return ObjectCreate;
		case 36:
			return ObjectDelete;
		case 37:
			return BlockPosition;
		case 38:
			return PlayMidi;
		case 39:
			return PlayWave;
		case 40:
			return guildList;
		case 41:
			return AreaChanged;
		case 42:
			return PauseToggle;
		case 43:
			return RainToggle;
		case 44:
			return CreateFX;
		case 45:
			return UpdateUserStats;
		case 46:
			return WorkRequestTarget;
		case 47:
			return ChangeInventorySlot;
		case 48:
			return ChangeBankSlot;
		case 49:
			return ChangeSpellSlot;
		case 50:
			return Atributes;
		case 51:
			return BlacksmithWeapons;
		case 52:
			return BlacksmithArmors;
		case 53:
			return CarpenterObjects;
		case 54:
			return RestOK;
		case 55:
			return ErrorMsg;
		case 56:
			return Blind;
		case 57:
			return Dumb;
		case 58:
			return ShowSignal;
		case 59:
			return ChangeNPCInventorySlot;
		case 60:
			return UpdateHungerAndThirst;
		case 61:
			return Fame;
		case 62:
			return MiniStats;
		case 63:
			return LevelUp;
		case 64:
			return AddForumMsg;
		case 65:
			return ShowForumForm;
		case 66:
			return SetInvisible;
		case 67:
			return DiceRoll;
		case 68:
			return MeditateToggle;
		case 69:
			return BlindNoMore;
		case 70:
			return DumbNoMore;
		case 71:
			return SendSkills;
		case 72:
			return TrainerCreatureList;
		case 73:
			return guildNews;
		case 74:
			return OfferDetails;
		case 75:
			return AlianceProposalsList;
		case 76:
			return PeaceProposalsList;
		case 77:
			return CharacterInfo;
		case 78:
			return GuildLeaderInfo;
		case 79:
			return GuildMemberInfo;
		case 80:
			return GuildDetails;
		case 81:
			return ShowGuildFundationForm;
		case 82:
			return ParalizeOK;
		case 83:
			return ShowUserRequest;
		case 84:
			return TradeOK;
		case 85:
			return BankOK;
		case 86:
			return ChangeUserTradeSlot;
		case 87:
			return SendNight;
		case 88:
			return Pong;
		case 89:
			return UpdateTagAndStatus;
		case 90:
			return SpawnList;
		case 91:
			return ShowSOSForm;
		case 92:
			return ShowMOTDEditionForm;
		case 93:
			return ShowGMPanelForm;
		case 94:
			return UserNameList;
		case 95:
			return ShowDenounces;
		case 96:
			return RecordList;
		case 97:
			return RecordDetails;
		case 98:
			return ShowGuildAlign;
		case 99:
			return ShowPartyForm;
		case 100:
			return UpdateStrenghtAndDexterity;
		case 101:
			return UpdateStrenght;
		case 102:
			return UpdateDexterity;
		case 103:
			return AddSlots;
		case 104:
			return MultiMessage;
		case 105:
			return StopWorking;
		case 106:
			return CancelOfferItem;
		}
		return null;
	}

	public static int toInteger(ServerPacketID x) {
		switch (x) {
		case Logged:
			return 0;
		case RemoveDialogs:
			return 1;
		case RemoveCharDialog:
			return 2;
		case NavigateToggle:
			return 3;
		case Disconnect:
			return 4;
		case CommerceEnd:
			return 5;
		case BankEnd:
			return 6;
		case CommerceInit:
			return 7;
		case BankInit:
			return 8;
		case UserCommerceInit:
			return 9;
		case UserCommerceEnd:
			return 10;
		case UserOfferConfirm:
			return 11;
		case CommerceChat:
			return 12;
		case ShowBlacksmithForm:
			return 13;
		case ShowCarpenterForm:
			return 14;
		case UpdateSta:
			return 15;
		case UpdateMana:
			return 16;
		case UpdateHP:
			return 17;
		case UpdateGold:
			return 18;
		case UpdateBankGold:
			return 19;
		case UpdateExp:
			return 20;
		case ChangeMap:
			return 21;
		case PosUpdate:
			return 22;
		case ChatOverHead:
			return 23;
		case ConsoleMsg:
			return 24;
		case GuildChat:
			return 25;
		case ShowMessageBox:
			return 26;
		case UserIndexInServer:
			return 27;
		case UserCharIndexInServer:
			return 28;
		case CharacterCreate:
			return 29;
		case CharacterRemove:
			return 30;
		case CharacterChangeNick:
			return 31;
		case CharacterMove:
			return 32;
		case ForceCharMove:
			return 33;
		case CharacterChange:
			return 34;
		case ObjectCreate:
			return 35;
		case ObjectDelete:
			return 36;
		case BlockPosition:
			return 37;
		case PlayMidi:
			return 38;
		case PlayWave:
			return 39;
		case guildList:
			return 40;
		case AreaChanged:
			return 41;
		case PauseToggle:
			return 42;
		case RainToggle:
			return 43;
		case CreateFX:
			return 44;
		case UpdateUserStats:
			return 45;
		case WorkRequestTarget:
			return 46;
		case ChangeInventorySlot:
			return 47;
		case ChangeBankSlot:
			return 48;
		case ChangeSpellSlot:
			return 49;
		case Atributes:
			return 50;
		case BlacksmithWeapons:
			return 51;
		case BlacksmithArmors:
			return 52;
		case CarpenterObjects:
			return 53;
		case RestOK:
			return 54;
		case ErrorMsg:
			return 55;
		case Blind:
			return 56;
		case Dumb:
			return 57;
		case ShowSignal:
			return 58;
		case ChangeNPCInventorySlot:
			return 59;
		case UpdateHungerAndThirst:
			return 60;
		case Fame:
			return 61;
		case MiniStats:
			return 62;
		case LevelUp:
			return 63;
		case AddForumMsg:
			return 64;
		case ShowForumForm:
			return 65;
		case SetInvisible:
			return 66;
		case DiceRoll:
			return 67;
		case MeditateToggle:
			return 68;
		case BlindNoMore:
			return 69;
		case DumbNoMore:
			return 70;
		case SendSkills:
			return 71;
		case TrainerCreatureList:
			return 72;
		case guildNews:
			return 73;
		case OfferDetails:
			return 74;
		case AlianceProposalsList:
			return 75;
		case PeaceProposalsList:
			return 76;
		case CharacterInfo:
			return 77;
		case GuildLeaderInfo:
			return 78;
		case GuildMemberInfo:
			return 79;
		case GuildDetails:
			return 80;
		case ShowGuildFundationForm:
			return 81;
		case ParalizeOK:
			return 82;
		case ShowUserRequest:
			return 83;
		case TradeOK:
			return 84;
		case BankOK:
			return 85;
		case ChangeUserTradeSlot:
			return 86;
		case SendNight:
			return 87;
		case Pong:
			return 88;
		case UpdateTagAndStatus:
			return 89;
		case SpawnList:
			return 90;
		case ShowSOSForm:
			return 91;
		case ShowMOTDEditionForm:
			return 92;
		case ShowGMPanelForm:
			return 93;
		case UserNameList:
			return 94;
		case ShowDenounces:
			return 95;
		case RecordList:
			return 96;
		case RecordDetails:
			return 97;
		case ShowGuildAlign:
			return 98;
		case ShowPartyForm:
			return 99;
		case UpdateStrenghtAndDexterity:
			return 100;
		case UpdateStrenght:
			return 101;
		case UpdateDexterity:
			return 102;
		case AddSlots:
			return 103;
		case MultiMessage:
			return 104;
		case StopWorking:
			return 105;
		case CancelOfferItem:
			return 106;
		}
		return 0;
	}
}
